language: node_js
dist: bionic
language: generic
node_js:
  - 12.16
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm link
  - cd ..
  - git clone https://gitlab.com/sequoia-pgp/sop-openpgp-js.git
  - cd sop-openpgp-js
  - npm install yargs
  - npm link openpgp
  - cd ..
  - curl https://gitlab.com/ilya_y_chesnokov/openpgp-interoperability-test-suite/-/archive/binary/openpgp-interoperability-test-suite-binary.tar.gz -O
  - tar -zxvf openpgp-interoperability-test-suite-binary.tar.gz
  - sudo apt-get -y install nettle-dev
  - cd openpgpjs
script:
  - $TRAVIS_BUILD_DIR/run-sop.sh
